### ISSUE TITLE
when I run some demo on android device,  I get some Error like this:

### ISSUE THREAD

**Issue by Mikkyyo** [justswaporg/justlists#2644]
when I run some demo on android device,  I get some Error like this:

     Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field IMPL_LOOKUP in class Ljava/lang/invoke/MethodHandles$Lookup; (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /system/framework/core-oj.jar)
        at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:46)
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:57)
        at feign.Feign$Builder.target(Feign.java:269)
        at feign.Feign$Builder.target(Feign.java:265)
        at org.xrpl.xrpl4j.client.JsonRpcClient.construct(JsonRpcClient.java:60)
        at org.xrpl.xrpl4j.client.XrplClient.<init>(XrplClient.java:92)

__Originally posted by @zhoushuntong in https://github.com/XRPLF/xrpl4j/issues/244__

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close
